const CartActionTypes = {
    TOGGLE_CART_HIDDEN:"TOGGLE_CART_HIDDEN",
    ADD_ITEM:"ADD_ITEM",
    REMOVE_ITEM:"REMOVE_ITEM",
    REMOVE_ALL_ITEMS:"REMOVE_ALL_ITEMS",
    CLEAR_ITEM_FROM_CART:"CLEAR_ITEM_FROM_CART",
    INCREASE_SIZE: "INCREASE_SIZE",
    DECREASE_SIZE: "DECREASE_SIZE",
    CLEAR_CART: "CLEAR_CART"
}

export default CartActionTypes